#include "test.h"
#define assert OS_ASSERT

THREAD_DECL(thread0, 1024);
THREAD_DECL(thread1, 1024);

static volatile int func1_count;
static volatile int func2_count;

static void* func1(void *a);
static void* func2(void *a);

//-----------------------------------------------------------------
// testcase:
//-----------------------------------------------------------------
void testcase(void * a)
{
    func1_count = func2_count = 0;

    THREAD_INIT(thread0, "thread0", func1, NULL, 5);
    THREAD_INIT(thread1, "thread1", func2, NULL, 5);

    // Background loop
    thread_sleep(25);
    assert(func1_count && func2_count);
    exit(0);
}

//-----------------------------------------------------------------
// func1:
//-----------------------------------------------------------------
static void* func1(void* a)
{
    int x;
    int i;

    while (1)
    {
        volatile int var = 0x1234;
        volatile unsigned int uvar = 0;
        volatile unsigned long longvar = 0;

        printf("\nTest:\n");

        printf("1. Initialised data\n");
        assert(var == 0x1234);  // .text
        assert(uvar == 0x0);    // .bss

        printf("2. Multiply\n");
        var = var * 3;
        assert(var == 13980);
        var = -1;
        var = var * 3;
        assert(var == -3);
        var = -5;
        var = var * 13;
        assert(var == -65);
        var = -5;
        var = var * -13;
        assert(var == (-5*-13));
        var = -123123415;
        var = var * 9664563;
        assert(var == (-123123415*9664563));

        printf("3. Divide\n");
        var = 13980;
        var = var / 5;
        assert(var == 2796);
        var = var % 100;
        assert(var == 96);
        var = -1273;
        var = var / 19;
        assert(var == -67);

        printf("4. Shift left\n");
        var = 0x1;
        var <<= 31;
        assert(var == 0x80000000);

        printf("5. Shift right\n");
        uvar = 0x80000000;
        uvar >>= 1;
        assert(uvar == 0x40000000);
        uvar >>= 30;
        assert(uvar == 0x00000001);

        printf("6. Shift right arithmetic\n");
        var = 0x80000000;
        var >>= 1;
        assert(var == 0xC0000000);

        printf("7. Signed comparision\n");
        var = -1;
        assert(var < 1);
        x = 10;
        assert(var < x);    
        assert(!(var > x)); 
        x = -3;
        assert(var > x);
        assert(x <= var);

        printf("8. Comparision\n");
        longvar = 0x1db9;
        if (longvar >= 0xFFF8 && longvar <= 0xFFFF) 
        {
            printf("- Incorrect comparision\n");
            assert(0);
        }

        func1_count += 1;
    }

    // Success
    return 0;
}
//-----------------------------------------------------------------
// func2:
//-----------------------------------------------------------------
static void* func2(void *a)
{
    while (1)
    {
    volatile unsigned int a = 28;
    volatile int b = 65521;
    volatile int c = -80;
    volatile unsigned char d = 67;
    c = b >= d;
    b = c ^ d;
    b = d > c;
    assert(b == 1);
    b = -7076;
    assert(c == 1);
    d = b > d;
    b = -25699;
    d = c >> a;
    a = b <= d;
    d = 115;
    assert(c == 1);
    a = c & c;
    d = c | d;
    c = b != c;
    c = b <= a;
    c = c - b;
    assert(a == 1);
    d = d != c;
    assert(a == 1);
    d = c & d;
    assert(c == 25699);
    c = 20;
    d = a >> c;
    d = a * c;
    d = 26;
    a = c & a;
    d = c + c;
    c = c != c;
    b = d + a;
    d = a <= a;
    d = d << a;
    b = a == c;
    a = c * a;
    c = 339;
    assert(d == 1);
    a = c == d;
    b = c < b;
    b = b ^ c;
    b = b > d;
    c = a == c;
    assert(c == 0);
    assert(c == 0);
    c = c != c;
    b = c <= a;
    b = a != c;
    d = c != b;
    c = b - c;
    b = b ^ a;
    assert(b == 0);
    d = 224;
    d = a | d;
    a = c != d;
    b = -126402;
    d = c * a;
    assert(d == 0);
    a = d - b;
    assert(a == 126402);
    a = c == c;
    d = b + a;
    assert(c == 0);
    b = 39462;
    c = d != c;
    c = a + c;
    b = -41083;
    assert(d == 63);
    b = b >= c;
    b = a < a;
    c = a == b;
    d = 27;
    b = a >> d;
    b = -18660;
    assert(c == 0);
    a = 3;
    a = c + a;
    b = 19;
    b = c >> b;
    assert(d == 27);
    b = d == b;
    assert(b == 0);
    b = c != a;
    a = a <= d;
    a = a & b;
    a = d < d;
    b = c >> d;
    a = 7;
    assert(d == 27);
    d = d < a;
    b = d & d;
    c = d - a;
    d = a + a;
    a = d < b;
    a = c ^ d;
    a = 26;
    assert(b == 0);
    assert(a == 26);
    b = d & b;
    d = d + c;
    a = c - b;
    d = d != b;
    d = a * c;
    b = d + a;
    b = 44080;
    a = d | b;
    b = a < b;
    a = c * c;
    d = 126;
    d = c | b;
    b = a | c;
    d = 234;
    d = c ^ d;
    d = a << d;
    b = d + a;
    assert(c == -7);
    c = c * a;
    b = -20292;
    b = a & b;
    d = d * b;
    a = 22;
    d = c << a;
    b = -107052;
    a = b == a;
    a = d - d;
    a = 31;
    a = a + b;
    c = d * a;
    assert(d == 0);
    assert(c == 0);
    assert(d == 0);
    assert(b == -107052);
    d = d > b;
    d = b - b;
    a = a - a;
    b = c < c;
    b = c << a;
    d = a << b;
    b = a >> b;
    b = 75097;
    b = b << d;
    b = d >> a;
    b = 30159;
    a = b | d;
    c = a >> c;
    d = a >= d;
    d = a + d;
    b = c != c;
    c = 409;
    c = a >= d;
    assert(c == 1);
    a = b ^ b;
    c = c << c;
    b = d >= d;
    b = -30117;
    c = a == c;
    b = -46167;
    c = -448;
    assert(b == -46167);
    assert(b == -46167);
    c = c + c;
    assert(b == -46167);
    c = -212;
    a = b < b;
    b = 22;
    b = d << b;
    d = 25;
    c = a << d;
    b = d <= b;
    a = d - c;
    b = a <= a;
    a = c | a;
    c = c >= c;
    d = b | b;
    assert(c == 1);
    b = -72284;
    b = a + a;
    a = 32;
    b = d == b;
    a = d == d;
    b = b + a;
    b = a <= c;
    a = c >= c;
    b = -115697;
    b = -114943;
    d = d * b;
    a = a << d;
    c = 330;
    a = a * b;
    b = 18;
    d = d << b;
    b = c >= a;
    b = c > c;
    a = a * d;
    c = 160;
    c = c * d;
    c = a == c;
    c = c <= c;
    a = 8;
    d = 142;
    b = c * a;
    b = d - c;
    d = d & d;
    d = 194;
    assert(b == 141);
    a = d == c;
    a = 22;
    b = d >= b;
    b = 81711;
    d = b + a;
    b = 23;
    c = d << b;
    c = b >= c;
    b = c < c;
    a = c + a;
    a = c - a;
    d = b <= d;
    b = b == a;
    d = c << b;
    c = c >> c;
    d = b + b;
    c = -352;
    b = d > d;
    d = 175;
    a = a | d;
    c = b | a;
    b = d + c;
    d = a >= a;
    c = -95;
    b = b >= b;
    d = 146;
    b = -24440;
    b = a + c;
    c = c >= d;
    c = a == c;
    d = d & a;
    b = d & d;
    assert(c == 0);
    d = b + c;
    d = c == d;
    c = b | d;
    d = a + a;
    d = 30;
    a = d >> d;
    d = d <= c;
    c = b < d;
    a = c * a;
    c = -234;
    b = 113349;
    c = c <= d;
    c = -345;
    c = d == c;
    d = c | b;
    d = a ^ a;
    d = c | c;
    assert(b == 113349);
    b = d - d;
    b = c ^ b;
    d = c < d;
    assert(c == 0);
    b = d | d;
    a = a > a;
    d = b | d;
    b = d >> a;
    a = c + b;
    b = c & a;
    b = a * a;
    assert(a == 0);
    assert(d == 0);
    d = b | c;
    b = b * a;
    c = -454;
    c = 131;
    d = b - c;
    c = d > a;
    assert(c == 1);
    d = a & d;
    a = c + c;
    a = 15;
    a = b == a;
    c = b ^ c;
    d = b - d;
    assert(a == 0);
    c = d * d;
    b = a + c;
    d = a - b;
    c = 212;
    b = d - a;
    a = 19;
    d = 49;
    b = b == a;
    a = c + c;
    d = 3;
    b = c >> d;
    assert(a == 424);
    assert(a == 424);
    b = d + b;
    d = c + b;
    b = a < c;
    a = d > c;
    d = 28;
    d = c >> d;
    c = a >= a;
    assert(b == 0);
    b = d & a;
    a = d != a;
    assert(a == 1);
    c = a * d;
    c = d != c;
    a = b == d;
    a = a ^ c;
    assert(d == 0);
    b = b <= b;
    b = c & b;
    d = d != d;
    a = c > b;
    assert(d == 0);
    b = -120194;
    assert(c == 0);
    c = c == a;
    b = c >= d;
    c = d | b;
    d = c <= d;
    d = a >= c;
    b = -58657;
    c = b | a;
    a = b - b;
    c = c ^ d;
    c = a > a;
    assert(b == -58657);
    c = c * b;
    assert(a == 0);
    d = b == c;
    c = -195;
    assert(c == -195);
    d = 175;
    b = 110627;
    c = c <= c;
    b = 29034;
    assert(b == 29034);
    d = b << a;
    assert(c == 1);
    assert(a == 0);
    assert(a == 0);
    d = c <= c;
    c = b * a;
    assert(c == 0);
    d = a == c;
    c = b * b;
    c = 6;
    d = b >> c;
    assert(a == 0);
    a = a != a;
    d = c > b;
    a = a < d;
    d = d & a;
    c = -10;
    assert(b == 29034);
    b = a <= a;
    d = b >> a;
    c = b & a;
    c = -269;
    assert(b == 1);
    d = 103;
    c = b != c;
    d = b != b;
    d = d >> d;
    b = b <= a;
    d = b != a;
    assert(d == 0);
    c = c ^ c;
    b = b * c;
    assert(d == 0);
    d = c * a;
    d = 93;
    a = a + b;
    a = c <= d;
    assert(b == 0);
    d = a > a;
    d = b << d;
    d = c & b;
    a = 20;
    a = d >= c;
    c = c != c;
    c = c ^ a;
    a = a * d;
    d = b == b;
    b = b == c;
    d = a >> a;
    a = c != a;
    d = b > b;
    a = 20;
    d = d - c;
    assert(c == 1);
    d = 196;
    b = c <= b;
    assert(d == 196);
    b = -80467;
    d = c << c;
    c = d <= c;
    assert(a == 20);
    c = a * a;
    b = 91936;
    assert(d == 2);
    d = b < c;
    b = 21;
    c = b << b;
    c = 252;
    d = b ^ b;
    d = c <= a;
    d = c << d;
    a = 16;
    assert(d == 252);
    c = -188;
    assert(d == 252);
    a = d < c;
    assert(a == 0);
    a = b == c;
    d = b < a;
    assert(d == 0);
    b = b + c;
    c = 386;
    a = b > a;
    d = 49;
    d = c & b;
    assert(a == 1);
    b = b | d;
    b = d & a;
    c = 17;
    c = d >> c;
    b = 125872;
    c = d | b;
    assert(d == 0);
    b = d <= d;
    a = 25;
    b = 114336;
    a = c * b;
    c = d == c;
    b = b << c;
    d = d > a;
    assert(a == 1506799104);
    a = 11;
    b = 88751;
    d = 107;
    d = 125;
    b = a ^ b;
    a = d > b;
    assert(d == 125);
    a = d * c;
    b = 30;
    a = b >> b;
    a = c == d;
    a = a < b;
    c = b > a;
    assert(c == 1);
    a = c & d;
    a = a >= d;
    b = 73656;
    d = a ^ a;
    a = c * b;
    a = a - d;
    d = d << c;
    b = 99702;
    a = a + a;
    a = 14;
    d = c << a;
    d = d | a;
    a = 12;
    d = c * c;
    b = c <= d;
    b = b >> b;
    a = 13;
    a = 25;
    d = a ^ a;
    assert(b == 0);
    d = c >> d;
    b = b - c;
    c = d - b;
    d = 1;
    d = d < a;
    d = b + d;
    assert(c == 2);
    d = b != d;
    b = b & b;
    d = c + d;
    assert(c == 2);
    a = 20;
    assert(a == 20);
    d = a + d;
    c = d << c;
    b = -40862;
    a = d >= c;
    assert(b == -40862);
    a = d * a;
    c = 5;
    b = c << c;
    d = 198;
    c = -18;
    c = a > d;
    d = c ^ c;
    d = 36;
    assert(b == 160);
    b = d != a;
    c = d << a;
    a = c & b;
    assert(d == 36);
    assert(b == 1);
    a = d <= a;
    d = d >= c;
    b = b | a;
    a = d + a;
    b = d ^ d;
    c = -177;
    a = c != a;
    b = b ^ b;
    a = b != b;
    b = b <= a;
    c = d < c;
    a = a & b;
    c = c == c;
    d = 190;
    d = 10;
    b = d ^ b;
    a = a << a;
    c = c + a;
    b = d > a;
    b = d + d;
    c = 388;
    c = d < d;
    assert(d == 10);
    assert(b == 20);
    assert(d == 10);
    c = d << a;
    d = c | d;
    c = b >= b;
    assert(b == 20);
    d = d == a;
    c = 50;
    assert(c == 50);
    b = c | c;
    c = a <= b;
    b = c != b;
    c = a | d;
    a = c ^ a;
    a = 30;
    d = b * d;
    a = d | d;
    assert(a == 0);
    b = 125859;
    assert(a == 0);
    c = b | c;
    d = 211;
    c = a != c;
    assert(c == 1);
    c = d >= a;
    d = c * a;
    c = -229;
    assert(d == 0);
    a = d ^ a;
    b = a > d;
    assert(b == 0);
    d = c < a;
    a = c * a;
    b = a <= b;
    a = b > d;
    c = c <= c;
    assert(d == 0);
    a = c != a;
    assert(a == 0);
    c = d << b;
    c = d - a;
    b = b == c;
    d = c * b;
    c = c + a;
    c = c << c;
    b = a * c;
    c = c <= a;
    assert(b == 0);
    c = c - a;
    d = a <= a;
    c = c != b;
    a = 20;
    a = b <= d;
    c = d ^ b;
    a = a >> a;
    b = 41728;
    c = d * a;
    b = c > c;
    a = d + a;
    c = -355;
    c = b == c;
    d = a ^ d;
    b = c + b;
    b = b ^ c;
    d = b < a;
    assert(c == 0);
    assert(c == 0);
    d = b - b;
    b = d > a;
    a = d & c;
    b = 74422;
    a = c & c;
    a = 21;
    c = -356;
    assert(a == 21);
    c = a > b;
    assert(d == 0);
    c = a - d;
    b = c + b;
    b = a | d;
    a = d == a;
    d = d ^ b;
    a = 32;
    d = b | b;
    a = c >= d;
    a = 2;
    d = b << c;
    c = c + a;
    a = b >> b;
    assert(c == 23);
    b = 91631;
    a = a | b;
    d = b * d;
    assert(c == 23);
    assert(a == 91631);
    b = c & d;
    b = a ^ d;
    a = 4;
    a = d >= c;
    c = c + c;
    a = a << d;
    b = c & b;
    d = b * a;
    d = 227;
    a = c > c;
    d = c < b;
    b = 18019;
    c = a >= a;
    c = b != b;
    b = c != c;
    assert(d == 0);
    c = b >> c;
    c = d > c;
    assert(b == 0);
    d = 180;
    c = 319;
    a = d | d;
    c = a >> b;
    b = a - c;
    b = 112013;
    b = b + a;
    b = c + c;
    c = -81;
    c = c + a;
    a = 25;
    d = b & d;
    c = c < c;
    b = 120394;
    d = d | c;
    assert(c == 0);
    c = a << a;
    a = a != b;
    d = 3;
    c = a >> d;
    a = 6;
    c = d << d;
    b = b + d;
    b = d * a;
    d = b >= d;
    a = d >> b;
    assert(c == 24);
    assert(b == 18);
    b = a != d;
    b = a + a;
    d = d - b;
    d = 20;
    assert(a == 0);
    b = -13796;
    c = d < c;
    b = d - c;
    c = a > d;
    c = d ^ d;
    assert(b == 19);
    a = c != a;
    d = b == b;
    c = 193;
    c = a >> a;
    assert(b == 19);
    a = c == d;
    d = a < d;
    a = 8;
    d = 253;
    c = a != b;
    d = 235;
    assert(d == 235);
    c = a <= c;
    b = -62638;
    d = d < c;
    a = c != c;
    d = c + b;
    c = b > d;
    a = 25;
    d = b << c;
    c = -484;
    b = 59387;
    c = d | c;
    assert(b == 59387);
    a = c != b;
    assert(a == 1);
    c = c - a;
    assert(c == -419);
    c = a < a;
    b = d ^ b;
    b = b >= b;
    b = b + c;
    d = c << c;
    d = c << d;
    d = c >> a;
    d = b << b;
    c = b & a;
    a = b - b;
    a = d * b;
    b = -87749;
    b = 56739;
    d = d ^ b;
    b = c * d;
    assert(c == 1);
    a = a & b;
    a = c & c;
    a = b >> a;
    b = d * c;
    c = 157;
    a = 9;
    b = b << a;
    b = c < d;
    d = d <= c;
    a = a >= b;
    assert(d == 0);
    c = d * b;
    c = b - b;
    b = -97375;
    assert(a == 1);
    a = 6;
    b = 100427;
    d = a - b;
    b = c - c;
    a = c | d;
    a = a <= c;
    assert(b == 0);
    c = c | d;
    c = b < d;
    a = c ^ a;
    assert(b == 0);
    d = 255;
    b = a >> b;
    a = d * b;
    d = a > a;
    c = c & d;
    a = 9;
    b = c < c;
    a = c >= d;
    a = a ^ c;
    assert(b == 0);
    b = d == a;
    b = c + c;
    c = d & a;
    a = a - d;
    a = 25;
    c = d != b;
    c = c != c;
    c = 69;
    d = 17;
    c = d >= d;
    b = b == d;
    assert(b == 0);
    b = c == b;
    b = -72630;
    b = 23;
    d = b << b;
    assert(d == 0);
    assert(c == 1);
    assert(a == 25);
    a = d * c;
    assert(a == 0);
    a = a - c;
    c = a < d;
    c = c * b;
    b = b <= d;
    a = c >= b;
    assert(b == 0);
    d = a > d;
    b = 11745;
    d = b == a;
    d = d & d;
    b = b > b;
    assert(d == 0);
    d = 160;
    d = c == d;
    d = 209;
    b = b + b;
    assert(a == 1);
    b = c << b;
    assert(a == 1);
    d = d << a;
    a = 5;
    assert(c == 0);
    b = c * d;
    assert(d == 162);
    c = a != d;
    b = c ^ b;
    d = 27;
    d = a << d;
    d = c ^ b;
    assert(a == 5);
    b = d >= c;
    d = 242;
    b = b > b;
    d = d + d;
    assert(c == 1);
    b = a ^ c;
    b = 74713;
    d = d | a;
    c = d > b;
    c = b - a;
    a = b ^ c;
    c = d != a;
    c = d | d;
    c = d & d;
    assert(d == 229);
    d = b & a;
    b = c | d;
    d = a << a;
    d = a ^ c;
    c = a - a;
    a = 4;
    d = b < d;
    b = c ^ c;
    a = 14;
    c = c <= d;
    b = a + a;
    a = d >= b;
    a = c - b;
    assert(d == 0);
    d = 105;
    b = c | b;
    d = d ^ c;
    c = 40;
    a = a * a;
    d = 140;
    b = d + b;
    d = 220;
    d = d <= c;
    c = c != b;
    b = d == c;
    assert(a == 729);
    a = b > c;
    a = d + d;
    c = a * b;
    d = a - b;
    d = c & b;
    assert(a == 0);
    c = b >= b;
    b = -107268;
    d = b == b;
    d = a >> d;
    c = a != d;
    b = d < b;
    a = c | a;
    a = a >= b;
    assert(d == 0);
    d = d != c;
    d = 42;
    c = d < c;
    b = c < b;
    c = d < d;
    c = a ^ a;
    assert(b == 0);
    d = a ^ c;
    assert(b == 0);
    a = a > d;
    c = a == c;
    d = 115;
    b = 124002;
    b = b == b;
    a = b == b;
    assert(d == 115);
    c = b + d;
    d = a < a;
    d = a >= d;
    a = c & a;
    d = c | b;
    c = a | b;
    b = a + d;
    assert(c == 1);
    assert(b == 117);
    c = 36;
    assert(c == 36);
    c = d * a;
    a = a + a;
    c = c | c;
    b = b | a;
    b = -73474;
    c = c | c;
    assert(c == 0);
    assert(a == 0);
    c = d ^ d;
    b = a >= c;
    c = 310;
    d = d & b;
    assert(c == 310);
    a = b ^ b;
    assert(a == 0);
    assert(c == 310);
    b = b == b;
    d = c | c;
    b = b != a;
    b = 63117;
    d = 15;
    a = a >> d;
    a = c - a;
    b = d - b;
    b = 17;
    c = a >> b;
    b = d | d;
    d = 212;
    a = d > b;
    a = a > b;
    d = a != b;
    a = 15;
    b = 60439;
    c = b + a;
    b = c >= d;
    a = b == b;
    b = 45282;
    b = a <= d;
    c = 473;
    a = c ^ c;
    b = b == a;
    c = d | c;
    c = 447;
    a = d & b;
    assert(c == 447);
    a = a != c;
    c = -263;
    d = b == d;
    d = c - b;
    d = 55;
    c = c ^ d;
    d = b | c;
    a = a > b;
    a = b < a;
    d = a - b;
    assert(a == 1);
    b = a >> a;
    c = c + a;
    a = b & d;
    d = d >= d;
    c = b | d;
    b = d >> d;
    b = b < b;
    d = a < c;
    d = a + a;
    assert(b == 0);
    c = a + c;
    assert(a == 0);
    c = d + a;
    d = c > a;
    c = 402;
    assert(d == 0);
    b = d >> d;
    assert(a == 0);
    b = d >> b;
    d = 242;
    c = b + d;
    d = c >= a;
    d = a < b;
    assert(b == 0);
    assert(d == 0);
    b = b >= a;
    d = b == b;
    c = c * b;
    c = c == a;
    a = 26;
    a = b | c;
    assert(b == 1);
    d = a != a;
    b = a ^ d;
    d = d != d;
    d = c & a;
    a = c + b;
    d = d <= c;
    b = c <= a;
    a = d < d;
    a = c <= d;
    d = b + d;
    assert(d == 2);
    assert(b == 1);
    d = d >> c;
    a = d << a;
    a = b >= a;
    d = 17;
    b = a * b;
    a = c >> a;
    b = a * c;
    a = b <= b;
    d = 171;
    c = d << b;
    d = 156;
    b = d >= b;
    d = d <= a;
    c = a << d;
    a = d + c;
    a = b << c;
    d = 12;
    a = 22;
    c = c | a;
    c = d + d;
    c = b * b;
    a = a >> a;
    b = a >> c;
    a = b >> d;
    assert(b == 0);
    b = b & d;
    b = 61364;
    d = a & b;
    c = c == d;
    c = c >= d;
    assert(d == 0);
    b = d >= b;
    assert(a == 0);
    d = b > a;
    d = 222;
    assert(a == 0);
    assert(d == 222);
    c = d > d;
    d = 107;
    b = b + c;
    d = c + c;
    a = a & c;
    a = d < b;
    a = 9;
    b = -14784;
    d = 248;
    c = a + c;
    b = a + d;
    c = b > c;
    b = 26;
    b = b >> b;
    c = d ^ c;
    c = c & c;
    b = b - c;
    assert(b == -249);
    d = c <= d;
    b = 6;
    b = a << b;
    c = 410;
    d = d | a;
    c = a & a;
    d = d >> d;
    c = b != b;
    assert(a == 9);
    a = a <= b;
    b = b ^ b;
    c = c - d;
    c = c & d;
    c = b * a;
    b = c <= b;
    d = d >= b;
    a = d & c;
    a = 22;
    b = 1788;
    assert(c == 0);
    b = -54740;
    a = a <= b;
    b = -124375;
    assert(b == -124375);
    b = b < b;
    a = a != a;
    d = b ^ d;
    d = 201;
    a = a > a;
    a = a | b;
    assert(b == 0);
    c = c != b;
    a = 12;
    a = 28;
    b = c - d;
    c = b <= a;
    b = 5;
    d = c >> b;
    d = c << a;
    c = 112;
    d = 14;
    a = 30;
    c = c >> b;
    c = b - b;
    b = d >> d;
    a = c - d;
    a = 10;
    a = c & d;
    d = c >> c;
    assert(b == 0);
    b = b + c;
    a = d - c;
    assert(c == 0);
    a = c > a;
    assert(b == 0);
    a = 2;
    b = b - c;
    c = a > a;
    d = d + b;
    b = d - c;
    assert(d == 0);
    d = c | d;
    a = c > b;
    assert(b == 0);
    assert(d == 0);
    a = d - a;
    a = 19;
    c = b - d;
    a = a * d;
    c = d * d;
    b = a << d;
    a = 4;
    d = 234;
    d = 72;
    d = a <= b;
    b = c < a;
    assert(d == 0);
    c = d == a;
    b = c ^ d;
    d = d == d;
    b = 25970;
    d = d << d;
    c = b > b;
    d = b != b;
    a = 26;
    a = b <= a;
    b = d - b;
    d = d - c;
    a = b >= b;
    d = d < b;
    b = 31;
    b = a << b;
    b = 49832;
    b = a >= c;
    c = a | b;
    c = c >> a;
    d = 153;
    assert(a == 1);
    a = c << b;
    a = 16;
    c = c + a;
    b = c ^ d;
    c = d * a;
    b = c != b;
    assert(c == 2448);
    c = b <= a;
    assert(b == 1);
    d = 87;
    c = c < a;
    c = c >> a;
    b = d + d;
    d = c > b;
    assert(d == 0);
    d = 137;
    assert(c == 0);
    d = b | a;
    a = 28;
    d = b << a;
    d = 194;
    c = a != d;
    d = 19;
    a = a << d;
    c = 144;
    b = a >= a;
    a = d > a;
    c = d >= c;
    d = a >> c;
    assert(a == 0);
    assert(d == 0);
    c = d >= d;
    a = b >= d;
    b = d << a;
    b = d - b;
    d = d - b;
    b = c - b;
    a = 10;
    b = b >> c;
    c = d + b;
    assert(b == 0);
    d = b << c;
    a = b <= d;
    c = a != a;
    c = b << b;
    assert(d == 0);
    c = b | b;
    c = c > b;
    assert(d == 0);
    assert(c == 0);
    c = a <= d;
    a = c != a;
    assert(b == 0);
    a = d + b;
    b = d >> b;
    c = b * d;
    c = d ^ b;
    assert(a == 0);
    d = c ^ d;
    c = d * a;
    a = d ^ a;
    assert(b == 0);
    a = c & c;
    b = d << c;
    assert(d == 0);
    a = 16;
    a = c & c;
    c = b * d;
    d = a >> d;
    assert(a == 0);
    d = d < c;
    b = -85932;
    a = d == b;
    d = 124;
    assert(d == 124);
    c = c + d;
    assert(c == 124);
    c = b * d;
    c = 291;
    c = a <= d;
    d = c ^ d;
    a = d << c;
    b = 6;
    c = d << b;
    assert(a == 250);
    c = 187;
    d = a < d;
    c = 176;
    a = a * c;
    c = c + c;
    d = b ^ b;
    assert(a == 44000);
    c = a * b;
    assert(c == 264000);
    a = a != c;
    b = c + c;
    a = a <= a;
    d = a & a;
    b = -108005;
    b = b + c;
    c = 22;
    a = a << c;
    assert(c == 22);
    b = -56748;
    a = b > c;
    d = b * c;
    a = d * c;
    d = 15;
    b = c << d;
    d = c & d;
    c = d <= d;
    c = c >= b;
    assert(c == 0);
    assert(b == 720896);
    assert(a == 1232);
    d = 129;
    assert(a == 1232);
    b = d < b;
    assert(c == 0);
    b = 11313;
    d = d <= d;
    a = 19;
    b = c << a;
    d = a >= b;
    a = b >> d;
    d = d | d;
    b = d < c;
    c = b <= c;
    b = -37847;
    c = a >> a;
    a = a >= d;
    a = a <= a;
    assert(c == 0);
    b = d + c;
    c = -96;
    assert(a == 1);
    a = a + a;
    assert(a == 2);
    assert(a == 2);
    c = 428;
    d = 76;
    b = c >> a;
    assert(b == 107);
    c = a ^ b;
    d = b * b;
    b = 82108;
    assert(c == 105);
    assert(c == 105);
    b = d == b;
    c = c & b;
    a = d - a;
    d = 30;
    c = d << d;
    c = a >> b;
    assert(b == 0);
    b = b <= c;
    c = b > a;
    c = c != b;
    d = b >> c;
    a = b << d;
    b = -117822;
    a = b >> a;
    b = b ^ a;
    assert(b == 76323);
    assert(a == 4294908385);
    c = d > c;
    assert(c == 0);
    c = d & a;
    assert(c == 0);
    assert(c == 0);
    assert(a == 4294908385);
    a = 4;
    a = a ^ a;
    b = b * b;
    c = -111;
    a = 23;
    b = b | a;
    b = c >> a;
    b = c + a;
    b = a >= d;
    d = c * d;
    assert(c == -111);
    assert(a == 23);
    c = 313;
    assert(a == 23);
    a = 11;
    c = d - b;
    a = 9;
    a = d == a;
    c = d & d;
    d = c >> a;
    b = b & d;
    c = 292;
    c = c * b;
    a = d < b;
    b = c + b;
    d = 79;
    d = c >= b;
    assert(c == 0);
    c = c * d;
    c = c & a;
    d = a * a;
    b = b >> d;
    a = c << d;
    assert(a == 0);
    d = c >= d;
    d = 213;
    c = d <= d;
    d = 209;
    b = 56901;
    assert(b == 56901);
    b = d <= c;
    a = 5;
    a = a >> c;
    a = 28;
    assert(d == 209);
    b = b & d;
    a = d != b;
    assert(b == 0);
    assert(d == 209);
    c = 426;
    d = d & a;
    d = c < a;
    b = c != b;
    a = c ^ b;
    b = 76696;
    a = b < b;
    c = -407;
    b = b << d;
    assert(b == 76696);
    assert(b == 76696);
    d = 67;
    b = c + b;
    c = 10;
    b = c << c;
    d = 4;
    c = d >> d;
    c = a | a;
    a = c << c;
    c = 393;
    a = c <= a;
    c = b & a;
    d = c >= a;
    a = 17;
    assert(a == 17);
    d = b <= b;
    c = c > a;
    assert(b == 10240);
    c = d ^ d;
    b = b & a;
    b = a <= a;
    assert(c == 0);
    assert(b == 1);
    b = b << c;
    a = 19;
    a = 1;
    b = a << a;
    c = b >= d;
    d = d < b;
    assert(b == 2);
    d = 103;
    a = 15;
    assert(c == 1);
    c = c | b;
    c = c > c;
    c = a >= b;
    assert(a == 15);
    d = a ^ c;
    a = c != b;
    assert(a == 1);
    b = d | a;
    c = d << b;
    b = d < b;
    assert(b == 1);
    c = b < b;
    assert(b == 1);
    b = c >= a;
    a = b == a;
    d = c << d;
    a = b * a;
    c = 441;
    c = a != a;
    a = c >= c;
    assert(c == 0);
    assert(c == 0);
    d = d > b;
    a = d >> b;
    a = d < c;
    a = b < b;
    a = 19;
    a = 1;
    assert(a == 1);
    d = c >> d;
    b = c * a;
    assert(d == 0);
    c = b >> c;
    assert(d == 0);
    assert(b == 0);
    b = c < d;
    d = d & b;
    b = d > b;
    b = a * a;
    b = -51063;
    assert(c == 0);
    d = b + c;
    c = d >= c;
    b = 7;
    c = b << b;
    b = a + a;
    d = 26;
    c = 24;
    b = d << c;
    b = b >= d;
    d = b < c;
    b = a * c;
    d = d >= b;
    a = d >= c;
    d = b << c;
    b = c >= a;
    a = a <= a;
    a = c >> d;
    c = c < c;
    b = 20735;
    a = b - d;
    d = c >> c;
    assert(a == 20735);
    c = a < d;
    assert(a == 20735);
    b = c >= c;
    assert(c == 0);
    c = a | c;
    assert(b == 1);
    c = -218;
    assert(a == 20735);
    c = 166;
    a = 3;
    a = c << a;
    a = 3;
    assert(b == 1);
    b = a >> d;
    assert(c == 166);
    b = a > c;
    b = 101699;
    a = d * b;
    d = b + c;
    a = c * a;
    assert(b == 101699);
    assert(c == 166);
    c = a | a;
    b = a >= d;
    assert(b == 0);
    c = b < c;
    d = d <= d;
    a = 28;
    c = b * d;
    d = c <= c;
    c = 324;
    b = 24983;
    b = a <= d;
    c = a != a;
    c = -16;
    assert(d == 1);
    a = 3;
    c = c - d;
    b = b > a;
    d = c > c;
    d = b << d;
    a = c >> a;
    d = 127;
    a = a - b;
    d = 17;
    c = c >> d;
    d = d * b;
    d = d - a;
    d = b & a;
    c = -315;
    b = 84160;
    a = b * a;
    a = a == b;
    a = a + c;
    a = d + d;
    b = b | c;
    d = b != b;
    a = 16;
    assert(b == -315);
    b = d & c;
    assert(a == 16);
    d = d & d;
    a = d >= d;
    c = a == d;
    b = -43934;
    d = a ^ c;
    b = c ^ b;
    assert(a == 1);
    b = d == b;
    a = 23;
    d = d >> b;
    d = c - c;
    a = a + b;
    c = a * b;
    a = c + b;
    d = c > d;
    assert(b == 0);
    b = 108068;
    b = d <= b;
    a = 3;
    d = a <= a;
    a = a ^ a;
    d = 253;
    b = d <= a;
    assert(b == 0);
    c = c - b;
    b = d >= c;
    b = 112850;
    assert(d == 253);
    c = d < b;
    b = d >> c;
    b = c < b;
    d = 31;
    d = d >> d;
    a = c == a;
    assert(c == 1);
    d = d <= d;
    c = b == d;
    c = d * b;
    assert(d == 1);
    d = c ^ d;
    d = b & d;
    a = b <= b;
    d = a & c;
    c = a >> c;
    d = d ^ c;
    b = -47156;
    b = c | b;
    b = a < c;
    a = d * d;
    c = d | d;
    c = c & b;
    assert(a == 1);
    d = 164;
    d = 14;
    b = a >> d;
    assert(d == 14);
    assert(a == 1);
    c = c <= c;
    assert(c == 1);
    d = c * b;
    b = -5582;
    b = 17;
    d = d >> b;
    c = b >= d;
    a = d <= a;
    a = 28;
    c = a + c;
    b = a - b;
    c = c | d;
    b = 41267;
    assert(c == 29);
    assert(d == 0);
    c = c == b;
    assert(b == 41267);
    assert(c == 0);
    a = 1;
    d = c - a;
    assert(b == 41267);
    d = c & d;
    b = d - a;
    d = 187;
    assert(b == -1);
    a = a << c;
    b = c << c;
    b = b ^ b;
    d = a < c;
    assert(c == 0);
    d = 254;
    b = c >= c;
    d = 22;
    b = a >> d;
    d = b != a;
    assert(d == 1);
    d = d << a;
    assert(b == 0);
    b = d == c;
    d = 184;
    c = c != d;
    a = 24;
    assert(d == 184);
    d = d > b;
    d = 33;
    d = a & c;
    assert(a == 24);
    b = b != b;
    c = c >> d;
    assert(d == 0);
    c = b == b;
    b = d & b;
    a = d >> b;
    assert(c == 1);
    assert(d == 0);
    assert(b == 0);
    assert(a == 0);
    a = a + c;
    assert(a == 1);
    assert(a == 1);
    assert(a == 1);
    a = d > a;
    assert(b == 0);
    a = d | d;
    assert(a == 0);
    c = d * c;
    c = b < c;
    d = c | c;
    b = c == c;
    b = b + a;
    d = d >= b;
    c = d <= a;
    a = b + d;
    b = d >= c;
    assert(b == 0);
    d = b != c;
    b = c << d;
    assert(b == 2);
    c = b > d;
    c = d & a;
    assert(b == 2);
    assert(b == 2);
    c = d * c;
    b = c < a;
    c = a * c;
    b = d <= c;
    c = c - a;
    d = 244;
    c = 195;
    d = 196;
    assert(a == 1);
    assert(a == 1);
    b = a <= c;
    d = c >= c;
    a = 27;
    d = b - c;
    d = a >= c;
    d = 122;
    assert(a == 27);
    b = d >= b;
    a = a <= c;
    assert(c == 195);
    a = c + b;
    c = c > c;
    a = 24;
    b = d <= c;
    d = d & d;
    b = a & b;
    b = a ^ c;
    a = b > b;
    d = a + d;
    assert(d == 122);
    a = b != b;
    c = d > c;
    c = d >= b;
    c = a != c;
    d = d >> b;
    d = a > b;
    d = 52;
    b = c >= b;
    assert(d == 52);
    b = d <= c;
    a = b != a;
    a = b >> b;
    c = b < a;
    c = d << b;
    a = d - b;
    d = a + a;
    c = b + a;
    c = -191;
    a = 25;
    assert(d == 104);
    assert(c == -191);
    assert(c == -191);
    c = a & c;
    c = a + a;
    d = 8;
    d = d << d;
    c = 179;
    b = c > d;
    a = 10;
    c = d + c;
    d = a - b;
    b = -12426;
    b = b <= c;
    d = d ^ b;
    d = d != a;
    c = 143;
    b = b != b;
    c = b * d;
    a = d ^ d;
    assert(a == 0);
    b = 6583;
    a = 30;
    a = a <= a;
    a = c <= c;
    b = -1703;
    c = d == c;
    a = b > a;
    c = c != a;
    b = d != a;
    d = b ^ c;
    d = d | b;
    c = a != d;
    a = 2;
    a = 16;
    a = c | c;
    c = a >> d;
    c = a > a;
    c = 77;
    a = b * b;
    b = d < a;
    assert(a == 0);
    d = b >> a;
    d = a & b;
    c = a & b;
    a = 28;
    a = d <= b;
    c = b * d;
    c = b + c;
    a = c * d;
    b = a * d;
    c = b != c;
    a = d != a;
    d = c * c;
    c = 99;
    assert(a == 0);
    assert(a == 0);
    d = 176;
    b = b <= d;
    c = a * d;
    b = 113086;
    a = b & c;
    a = d < a;
    a = d | a;
    d = 21;
    a = 11;
    assert(b == 113086);
    a = b | d;
    b = -16395;
    b = d != a;
    d = d * d;
    assert(d == 185);
    d = d < c;
    assert(d == 0);
    a = a - d;
    d = 231;
    d = c == c;
    c = c != b;
    b = d + d;
    d = b * d;
    assert(c == 1);
    c = d == b;
    a = 24;
    d = c <= b;
    c = 355;
    c = -201;
    assert(c == -201);
    assert(c == -201);
    a = 7;
    assert(c == -201);
    d = b | b;
    a = d << b;
    d = d | c;
    d = a > a;
    assert(a == 8);
    a = a < c;
    a = 9;
    c = c <= a;
    a = b + b;
    assert(d == 0);
    assert(b == 2);
    d = 171;
    assert(a == 4);
    b = c << b;
    assert(a == 4);
    assert(b == 0);
    assert(d == 171);
    a = b | a;
    assert(c == 0);
    d = 203;
    b = c >= a;
    b = c >= c;
    b = a > c;
    c = d + a;
    assert(c == 207);
    b = 96471;
    b = a < d;
    d = 38;
    b = b == a;
    c = a - d;
    c = -53;
    c = c >= a;
    c = d <= b;
    a = a | a;
    a = a >= b;
    d = a == c;
    c = d == a;
    d = a + b;
    a = 7;
    c = d << a;
    assert(d == 1);
    c = c > b;
    b = a - c;
    assert(a == 7);
    b = b >> d;
    a = b + c;
    a = d == c;
    c = b == a;
    assert(b == 3);
    d = 200;
    a = 4;
    d = b - c;
    assert(a == 4);
    c = c * d;
    assert(d == 3);
    c = c < a;
    d = c >= a;
    d = d - a;
    a = 23;
    c = d | b;
    assert(c == 255);
    c = c & b;
    a = d ^ d;
    c = c - d;
    c = b <= d;
    assert(d == 252);
    b = d >= c;
    b = -119210;
    b = -31832;
    d = 4;
    a = a >> d;
    d = a != a;
    d = a ^ d;
    b = d - a;
    c = b * c;
    c = a == b;
    assert(c == 1);
    assert(b == 0);
    assert(d == 0);
    assert(b == 0);
    a = d >= d;
    b = a << c;
    b = a - d;
    a = c - a;
    a = c - c;
    b = d | a;
    d = a & c;
    d = c * d;
    c = 261;
    a = b != c;
    b = 113944;
    d = a < b;
    b = d * c;
    c = a << d;
    a = a * a;
    a = 15;
    d = d - a;
    d = 27;
    a = d << d;
    assert(b == 261);
    d = b == b;
    c = c | a;
    a = d == a;
    a = b != b;
    b = c - c;
    b = a << a;
    assert(a == 0);
    d = d & c;
    c = c == b;
    a = b + d;
    a = c == c;
    b = b & a;
    b = d >> b;
    c = c | c;
    d = a != c;
    a = 31;
    b = a != d;
    c = d <= d;
    a = c | b;
    c = c == c;
    assert(d == 1);
    b = b > c;
    a = 29;
    assert(a == 29);
    b = b & c;
    c = -167;
    assert(b == 0);
    a = 6;
    d = a < b;
    c = b & c;
    b = a * b;
    assert(a == 6);
    d = 62;
    b = c + c;
    c = -473;
    a = a >> b;
    d = 246;
    assert(d == 246);
    d = 27;
    b = a >> d;
    b = d - a;
    b = d * d;
    a = c & a;
    a = b != b;
    b = d * a;
    d = b ^ b;
    b = 57398;
    d = a > c;
    c = 408;
    d = c != d;
    b = b - c;
    assert(c == 408);
    c = b ^ b;
    assert(b == 56990);
    assert(d == 1);
    d = a >= c;
    assert(c == 0);
    d = d > a;
    b = 90073;
    b = a > c;
    a = 13;
    a = d >= d;
    c = a >> c;
    d = 186;
    d = 24;
    d = b << d;
    b = b * a;
    b = a == b;
    a = c | d;
    a = a >= b;
    b = -69478;
    d = a ^ d;
    b = a >= a;
    a = d - a;
    assert(b == 1);
    assert(b == 1);
    assert(d == 1);
    d = d <= d;
    d = 255;
    a = b != b;
    a = a - d;
    assert(a == 4294967041);
    a = 30;
    assert(d == 255);
    c = b == c;
    a = c - d;
    assert(c == 1);
    d = d << b;
    a = b * a;
    d = 240;
    d = d != d;
    a = a < a;
    c = 310;
    assert(d == 0);
    d = c - c;
    b = d == a;
    d = c != c;
    a = c | c;
    assert(b == 1);
    assert(a == 310);
    d = c >> d;
    a = a & c;
    c = a * b;
    assert(d == 54);
    assert(b == 1);
    a = 26;
    b = d <= c;
    a = a > b;
    c = a | c;
    d = 1;
    d = c >> d;
    assert(c == 311);
    a = a <= b;
    a = 8;
    assert(c == 311);
    d = c ^ c;
    c = c ^ d;
    assert(b == 1);
    d = a * c;
    a = 18;
    c = d >= b;
    d = c >= a;
    b = b >= c;
    a = b <= d;
    d = a ^ c;
    assert(a == 0);
    c = -421;
    d = c <= c;
    a = c >> d;
    c = 492;
    b = d + a;
    c = -420;
    d = 224;
    c = c & d;
    d = a + d;
    b = 96654;
    b = d << d;
    b = c >= a;
    d = 215;
    assert(c == 64);
    a = 19;
    c = a != b;
    b = d * b;
    assert(d == 215);
    a = c >= d;
    c = -72;
    d = b != c;
    b = -67388;
    d = c != d;
    d = c >> d;
    b = a == a;
    d = a >= c;
    b = b << b;
    d = 56;
    assert(c == -72);
    b = -78217;
    assert(a == 0);
    c = 361;
    c = d == a;
    b = 17;
    d = a << b;
    a = 23;
    b = a >= b;
    a = 8;
    a = a >= a;
    b = c >= d;
    c = b != a;
    a = c + d;
    b = a << d;
    b = b >= a;
    d = b >= c;
    d = c == d;
    assert(a == 0);
    d = a < c;
    d = 95;
    c = c >> c;
    assert(a == 0);
    b = d >= a;
    a = 21;
    b = a >= d;
    a = c + c;
    c = -226;
    c = c < a;
    d = c >= c;
    b = b * a;
    a = a + a;
    b = a >= c;
    c = c | d;
    assert(b == 1);
    c = a & c;
    d = 118;
    c = b + b;
    c = c == d;
    a = d > d;
    d = 8;
    c = -227;
    c = b * a;
    c = a <= c;
    d = c >= d;
    a = d <= c;
    c = -203;
    b = -120323;
    b = 14979;
    a = b * a;
    c = 60;
    d = d | b;
    a = b <= b;
    d = c != c;
    d = 16;
    assert(a == 1);
    c = c <= a;
    c = d + c;
    d = d != a;
    d = 203;
    c = c & b;
    assert(a == 1);
    b = d & a;
    d = a >> c;
    b = b + d;
    a = 28;
    c = b * c;
    assert(c == 0);
    d = a >> d;
    b = a ^ c;
    a = d + c;
    b = d & c;
    assert(a == 14);
    assert(b == 0);
    c = d & a;
    a = b & b;
    a = c | a;
    d = 171;
    d = c == c;
    d = c == c;
    c = c & b;
    a = 4;
    assert(b == 0);
    d = a & c;
    c = b == d;
    c = 362;
    c = b >> d;
    assert(d == 0);
    c = 3;
    a = d & c;
    a = a <= d;
    a = c + c;
    assert(b == 0);
    a = 19;
    a = 29;
    a = a < d;
    d = b > b;
    b = d + d;
    a = c > c;
    a = a < a;
    d = c - d;
    a = c - d;
    c = b == a;
    a = c == c;
    b = b >> b;
    c = a | b;
    b = d >= a;
    c = d <= a;
    c = c * b;
    assert(b == 1);
    a = a < c;
    a = 18;
    b = b <= a;
    d = b ^ c;
    d = d - a;
    a = c * c;
    b = a < b;
    d = 10;
    d = a >> d;
    d = b <= b;
    c = a != a;
    d = 215;
    assert(a == 0);
    c = 234;
    d = c > a;
    d = a >= d;
    assert(a == 0);
    a = b - d;
    c = d | a;
    c = c == d;
    assert(c == 0);
    d = c > a;
    a = 14;
    a = b >> c;
    a = a & c;
    b = -117901;
    b = 118888;
    c = a != c;
    b = b != b;
    c = a | d;
    a = c * a;
    c = d <= b;
    d = b <= c;
    a = b | a;
    d = a & c;
    d = c + d;
    a = d > d;
    c = b ^ d;
    a = c << c;
    c = -30;
    c = b >= d;
    c = 280;
    d = b != b;
    b = a | b;
    assert(d == 0);
    assert(b == 2);
    d = 178;
    assert(c == 280);
    c = c <= a;
    a = d + d;
    a = b ^ c;
    c = 265;
    b = -125091;
    d = d > a;
    d = 82;
    a = b + b;
    d = b == a;
    assert(c == 265);
    a = 2;
    c = b >> a;
    assert(b == -125091);
    b = 87127;
    c = -291;
    d = 26;
    b = c < d;
    d = d + c;
    d = b < a;
    b = a != a;
    a = b + d;
    c = b & d;
    c = d << a;
    b = a + d;
    c = c + c;
    assert(c == 4);
    b = d << c;
    assert(d == 1);
    c = b + a;
    assert(a == 1);
    c = b >= b;
    d = a != d;
    a = b & b;
    assert(c == 1);
    d = b & a;
    a = 16;
    a = a | b;
    a = b ^ d;
    c = b < c;
    a = 29;
    d = b >= d;
    b = -20555;
    b = b - a;
    b = b <= a;
    c = a <= d;
    a = c != b;
    c = b == b;
    c = 319;
    d = a >> a;
    assert(a == 0);
    a = c <= a;
    a = b ^ b;
    b = a != b;
    a = c <= b;
    b = b << b;
    b = a ^ d;
    c = b >= b;
    a = c + d;
    d = c ^ c;
    a = c & b;
    d = 184;
    a = a << c;
    a = c >= d;
    d = a != b;
    d = 23;
    a = 15;
    d = d - d;
    a = a + d;
    assert(a == 15);
    c = b | c;
    c = c != c;
    d = a | c;
    c = a >> b;
    b = a & a;
    d = 119;
    a = d < b;
    c = 161;
    c = c & b;
    a = d != a;
    a = b != a;
    assert(c == 1);
    assert(b == 15);
    assert(b == 15);
    b = 110154;
    d = d * b;
    d = 248;
    assert(a == 1);
    a = a ^ a;
    b = c != a;
    b = d > d;
    b = d >> a;
    c = b + b;
    a = b >= d;
    c = c | d;
    b = b - c;
    b = a > a;
    assert(c == 504);
    assert(d == 248);
    c = c == d;
    b = -122854;
    a = d | a;
    a = a == b;
    c = b >= b;
    c = a ^ a;
    a = c * c;
    a = 5;
    a = c | a;
    c = -226;
    a = 24;
    assert(a == 24);
    d = a + a;
    a = d - a;
    assert(b == -122854);
    d = d <= d;
    b = 22;
    b = a << b;
    b = 48071;
    c = a & d;
    a = b + a;
    a = 14;
    b = -121884;
    assert(b == -121884);
    assert(c == 0);
    a = a > a;
    b = 110250;
    b = c * c;
    a = a <= b;
    a = 26;
    b = a != d;
    d = b * d;
    a = a < c;
    assert(a == 0);
    c = d ^ b;
    a = a <= c;
    a = 6;
    d = 162;
    c = b + a;
    d = d >= c;
    assert(d == 1);
    b = b < d;
    assert(a == 6);
    assert(c == 7);
    a = d > a;
    b = b >= c;
    c = -9;
    d = a & b;
    d = c & d;
    c = -480;
    b = b & a;
    b = a < d;
    b = d == d;
    assert(d == 0);
    d = a != a;
    assert(a == 0);
    c = c > c;
    c = a | a;
    a = b != b;
    b = b ^ a;
    assert(a == 0);
    c = b ^ c;
    c = d - c;
    c = a >> d;
    b = c | d;
    d = a < c;
    b = -106323;
    a = c - b;
    assert(b == -106323);
    d = c | b;
    a = 3;
    c = c < a;
    a = a * d;
    b = a & c;
    c = d << b;
    assert(b == 1);
    c = -477;
    d = c & d;
    a = 19;
    assert(c == -477);
    c = b * a;
    a = b == c;
    b = -8396;
    assert(a == 0);
    a = b == a;
    assert(a == 0);
    c = c + b;
    a = 19;
    d = 6;
    c = d > b;
    c = d << c;
    a = 20;
    assert(d == 6);
    a = d << a;
    b = d << d;
    c = b | d;
    c = a - a;
    b = a | b;
    c = d | c;
    c = 233;
    c = d > c;
    a = 2;
    b = d >> a;
    c = b + b;
    b = c + d;
    d = 182;
    b = d - c;
    assert(b == 180);
    b = c > a;
    a = 6;
    c = -158;
    b = c | d;
    c = c | c;
    a = c - c;
    a = c + d;
    c = c != d;
    b = c + c;
    d = 101;
    c = c * a;
    assert(d == 101);
    d = b & a;
    b = a + c;
    d = c << a;
    a = b != b;
    c = d <= b;
    b = b != c;
    c = -444;
    d = 36;
    b = d == d;
    a = a >> b;
    b = b | a;
    c = 324;
    assert(d == 36);
    d = d * c;
    b = c | d;
    d = 24;
    c = d | b;
    d = d * a;
    c = b >= a;
    assert(b == 468);
    b = 12;
    c = a >> b;
    c = b < a;
    b = c + c;
    c = d << c;
    d = d * c;
    b = d & c;
    b = 57371;
    c = b == b;
    b = c == c;
    assert(d == 0);
    a = 12;
    c = d < a;
    c = c != a;
    d = b >> d;
    assert(b == 1);
    assert(a == 12);
    a = c & d;
    a = b | c;
    c = -463;
    assert(c == -463);
    c = -410;
    d = d != c;
    b = c <= c;
    a = 17;
    c = c != c;
    a = a ^ b;
    b = b << a;
    d = 200;
    b = c - c;
    d = d + d;
    b = a + d;
    a = c | d;
    a = 16;
    d = a & c;
    c = d >> d;
    b = c >= a;
    d = b >> b;
    c = b & b;
    a = d | d;
    a = b >= c;
    d = c * d;
    a = b <= d;
    b = b >> d;
    b = 101550;
    a = c + b;
    d = 70;
    d = 148;
    assert(b == 101550);
    d = 146;
    d = d < d;
    d = a > b;
    d = c * a;
    assert(c == 0);
    b = d >= b;
    d = d & b;
    a = 30;
    c = d - d;
    d = c >> b;
    b = b + c;
    d = 160;
    a = d > c;
    assert(d == 160);
    c = b & c;
    c = c >> c;
    b = b << a;
    b = c & d;
    a = d != b;
    d = d > b;
    b = a - d;
    a = 23;
    assert(d == 1);
    d = b ^ b;
    assert(d == 0);
    b = a == d;
    d = d ^ c;
    c = a <= d;
    a = b >> c;
    assert(b == 0);
    b = c ^ c;
    c = a > a;
    c = b < a;
    d = d <= b;
    c = b ^ b;
    assert(d == 1);
    a = c < b;
    b = -121388;
    a = d & a;
    b = d <= a;
    a = b + b;
    c = a & c;
    assert(d == 1);
    d = a << c;
    assert(d == 0);
    assert(c == 0);
    b = c << c;
    b = d != a;
    a = d + a;
    d = c - b;
    b = -112299;
    d = d > b;
    c = b | d;
    assert(a == 0);
    b = d * b;
    d = b >= c;
    b = c ^ c;
    assert(a == 0);
    a = b <= b;
    d = b * a;
    assert(d == 0);
    b = d ^ a;
    assert(b == 1);
    a = b ^ c;
    b = d + c;
    b = d < b;
    b = c | a;
    assert(a == 4294854996);
    d = d ^ c;
    a = c != a;
    assert(a == 1);
    assert(d == 85);
    assert(d == 85);
    assert(d == 85);
    d = b > c;
    assert(d == 0);
    c = 210;
    a = c + b;
    assert(c == 210);
    d = a ^ b;
    assert(c == 210);
    b = d != a;
    d = c != c;
    a = 25;
    d = b * d;
    b = a ^ a;
    assert(b == 0);
    assert(d == 0);
    c = 7;
    b = d >> c;
    b = a ^ d;
    c = d ^ a;
    c = 279;
    a = 6;
    assert(d == 0);
    d = a != c;
    a = b * d;
    b = 116370;
    assert(b == 116370);
    b = d < c;
    assert(b == 1);
    d = d - a;
    b = b * d;
    b = a != d;
    a = b != a;
    b = b < c;
    a = c >= b;
    b = c > a;
    d = b == d;
    assert(d == 0);
    b = d | d;
    a = a > d;
    b = b <= c;
    c = d > c;
    d = a != b;
    c = b < b;
    assert(d == 0);
    d = 115;
    a = d >> a;
    b = 41545;
    c = c - c;
    d = c ^ c;
    b = -22665;
    c = d | c;
    a = a - d;
    a = a ^ c;
    b = d < c;
    b = c >= c;
    b = d | d;
    d = c ^ c;
    b = d ^ b;
    d = d << d;
    assert(d == 0);
    c = a > a;
    c = c >> c;
    assert(d == 0);
    b = a != d;
    a = 25;
    c = a >= b;
    b = c > a;
    assert(c == 1);
    assert(b == 0);
    b = c * c;
    assert(c == 1);
    c = b >= d;
    d = c <= b;
    b = c < a;
    c = a + b;
    c = d == d;
    assert(c == 1);
    assert(a == 25);
    d = 163;
    b = 90909;
    assert(a == 25);
    d = a - d;
    c = a - a;
    d = d < c;
    b = a ^ b;
    c = b - b;
    assert(b == 90884);
    b = 4;
    d = c << b;
    b = b == a;
    assert(d == 0);
    assert(a == 25);
    b = a > d;
    c = -185;
    b = a >> a;
    assert(d == 0);
    b = d >= d;
    d = 196;
    d = b ^ b;
    c = d > d;
    b = c & b;
    a = 15;
    assert(d == 0);
    assert(d == 0);
    d = b <= c;
    c = c * c;
    d = c << c;
    c = 26;
    assert(b == 0);
    b = -115406;
    c = d << a;
    c = a >= b;
    b = 7;
    a = a >> b;
    c = a + a;
    assert(b == 7);
    d = 72;
    d = 149;
    b = d - a;
    b = -124671;
    b = 88677;
    b = a * b;
    d = a >> c;
    d = b - d;
    a = d != c;
    b = b != b;
    a = 24;
    a = d + a;
    d = b <= a;
    c = b * a;
    d = c * c;
    b = c < c;
    d = c >> a;
    d = b >= a;
    b = d >> c;
    b = c | c;
    d = a & d;
    assert(b == 0);
    d = b != a;
    c = d & d;
    a = d << d;
    c = c << d;
    c = -227;
    c = 3;
    b = c >> c;
    a = c == b;
    a = c < b;
    c = c == b;
    c = a < b;
    d = d <= a;
    a = d > b;
    c = -262;
    d = b - d;
    d = 246;
    a = a != d;
    b = d * c;
    d = c > a;
    assert(d == 1);
    b = -20944;
    b = c * b;
    a = b & b;
    d = 7;
    assert(c == -262);
    d = b + b;
    c = b & c;
    b = -123690;
    assert(c == 5487328);
    b = b * a;
    a = d < c;
    a = d < a;
    a = a | a;
    c = 432;
    a = b == c;
    a = 4;
    assert(a == 4);
    c = d >= a;
    b = b ^ a;
    b = d - c;
    b = d & c;
    c = 286;
    d = a - a;
    c = d >> b;
    a = d & c;
    c = a + b;
    c = b * d;
    a = a & a;
    c = c <= b;
    c = a <= c;
    d = b <= d;
    assert(c == 1);
    assert(c == 1);
    b = -53217;
    b = d == a;
    b = c > d;
    c = b < b;
    c = 439;
    c = -405;
    a = d < b;
    assert(a == 0);
    b = d < b;
    c = 7;
    a = c << c;
    a = c ^ a;
    d = a + d;
    assert(a == 903);
    c = c != d;
    c = a >> b;
    c = c * c;
    assert(a == 903);
    a = c & a;
    assert(a == 257);
    b = a & a;
    b = 8;
    b = d << b;
    a = a | b;
    a = a > a;
    c = a & b;
    c = 169;
    d = c | c;
    d = 166;
    d = d ^ d;
    d = d > d;
    assert(d == 0);
    d = c > d;
    c = c != c;
    d = a > b;
    assert(c == 0);
    a = a - a;
    b = -101674;
    c = c << c;
    d = d == a;
    b = b - b;
    a = 2;
    b = 11426;
    a = c & a;
    a = b >= c;
    c = d + b;
    c = a ^ b;
    b = d * b;
    b = -84480;
    assert(d == 1);
    d = a >= d;
    assert(b == -84480);
    a = c >= a;
    d = c >= d;
    a = b == c;
    a = d > c;
    b = b ^ d;
    c = c - a;
    assert(c == 11427);
    assert(a == 0);
    d = d + b;
    b = c << d;
    b = d & a;
    c = d > d;
    a = d == a;
    a = 14;
    b = a >> d;
    b = b ^ b;
    c = b == b;
    d = a == c;
    d = a < a;
    c = -112;
    c = b ^ a;
    c = 32;
    b = 78442;
    b = d == d;
    c = d <= d;
    d = 143;
    c = c & c;
    a = 30;
    assert(a == 30);
    assert(b == 1);
    d = c > a;
    d = c & a;
    c = c | c;
    d = 89;
    d = 11;
    c = d >> d;
    d = c < d;
    c = -300;
    b = b < d;
    c = a + c;
    a = c > d;
    d = a < a;
    a = 14;
    a = d >= a;
    d = 247;
    a = d * c;
    a = 8;
    a = d <= d;
    assert(b == 0);
    c = c <= d;
    a = 15;
    a = b <= a;
    a = b * d;
    c = c + c;
    d = a < b;
    c = b * a;
    d = 100;
    c = d ^ d;
    a = d & c;
    a = c == c;
    b = 103749;
    d = 4;
    a = b == c;
    assert(a == 0);
    d = c | c;
    c = d * b;
    d = 34;
    c = b > c;
    d = 2;
    a = d >> d;
    c = b << c;
    c = 71;
    a = 22;
    d = 87;
    b = d != a;
    assert(c == 71);
    assert(d == 87);
    c = d & d;
    d = c + c;
    b = c - a;
    d = a ^ c;
    d = d * b;
    a = a * a;
    a = 24;
    d = d >> a;
    d = a > c;
    c = -459;
    assert(d == 0);
    c = -286;
    d = c & a;
    a = b < a;
    assert(d == 0);
    d = d & c;
    a = d == a;
    a = b | b;
    a = 9;
    b = 28841;
    d = d <= c;
    b = d - b;
    a = c > c;
    a = d <= d;
    assert(a == 1);
    a = d & a;
    a = 14;
    assert(a == 14);
    b = b == b;
    d = c | c;
    c = b * a;
    a = b < b;
    d = c >= b;
    a = 32;
    a = a | b;
    c = d & d;
    d = c & c;
    b = a * d;
    assert(b == 33);
    assert(c == 1);
    c = -468;
    a = 24;
    b = a >> a;
    d = d - b;
    assert(d == 1);
    assert(a == 24);
    a = 9;
    d = c & a;
    a = d == b;
    b = b >> a;
    a = 3;
    a = d | b;
    b = -43775;
    c = b >= b;
    d = d < b;
    c = c < a;
    b = 58929;
    d = d != c;
    assert(c == 1);
    assert(a == 8);
    d = d - c;
    c = b * a;
    c = a - b;
    b = d ^ c;
    assert(b == -58921);
    assert(b == -58921);
    d = c > c;
    b = 1;
    d = a << b;
    d = b | c;
    d = a ^ c;
    d = a == a;
    d = b > a;
    b = b - a;
    b = b ^ c;
    assert(b == 58926);
    assert(d == 0);
    b = -52368;
    d = a == d;
    b = c ^ d;
    d = 7;
    assert(d == 7);
    c = a > d;
    assert(a == 8);
    a = 32;
    assert(a == 32);
    d = d == c;
    c = -351;
    b = a - c;
    a = b * d;
    c = 80;
    d = 137;
    b = d <= c;
    d = 12;
    d = d >> d;
    a = 16;
    b = d << b;
    d = b < d;
    b = b + b;
    d = d | a;
    assert(a == 16);
    d = a & d;
    b = a << a;
    a = d - a;
    assert(c == 80);
    assert(c == 80);
    b = c == b;
    a = d >= c;
    d = d > b;
    c = b - b;
    b = c <= d;
    assert(c == 0);
    assert(b == 1);
    a = d - a;
    a = c ^ b;
    b = b != b;
    assert(b == 0);
    b = b - b;
    d = d >> b;
    c = a >= d;
    a = d >> b;
    a = d ^ a;
    b = d == b;
    a = c - d;
    c = d | c;
    a = a != d;
    b = d - d;
    b = a << c;
    c = c == d;
    a = 2;
    assert(c == 1);
    assert(a == 2);
    a = 9;
    a = 32;
    c = b * c;
    a = 5;
    d = b == b;
    b = d & a;
    b = a & c;
    b = b & d;
    assert(c == 2);
    d = 216;
    d = d | b;
    assert(d == 216);
    a = c & d;
    a = c >= d;
    b = d >= b;
    a = a + b;
    assert(c == 2);
    a = c + d;
    c = -233;
    d = 71;
    assert(a == 218);
    d = d >> b;
    b = -28080;
    a = 17;
    d = c >> a;
    a = a > d;
    c = 278;
    d = c + d;
    c = c + c;
    b = c <= a;
    d = a > c;
    assert(b == 0);
    assert(a == 0);
    c = c == c;
    b = b - c;
    c = b < a;
    a = c != d;
    a = b < c;
    b = 119522;
    d = a >= d;
    assert(b == 119522);
    a = a - d;
    b = d * c;
    b = 39426;
    a = c <= c;
    c = b == b;
    c = d <= b;
    d = d * b;
    a = 12;
    d = 61;
    assert(b == 39426);
    c = c < a;
    assert(b == 39426);
    d = 148;
    d = a + b;
    b = d * b;
    assert(d == 14);
    a = a - b;
    d = c < b;
    d = c + b;
    a = b >= c;
    d = a | a;
    b = d >> d;
    assert(d == 1);
    c = a << b;
    assert(a == 1);
    d = 49;
    d = 18;
    c = a << d;
    a = c <= c;
    b = a & b;
    a = c <= d;
    c = 28;
    d = b << c;
    d = d == d;
    b = d != b;
    b = 26350;
    assert(b == 26350);
    a = d ^ b;
    b = c + b;
    a = d >= c;
    assert(c == 28);
    b = -16458;
    assert(c == 28);
    a = a == c;
    b = 5;
    b = c >> b;
    d = a >> c;
    a = c <= b;
    b = a >= b;
    c = -318;
    d = d == a;
    d = b >= c;
    d = d << b;
    a = 6;
    a = b & b;
    a = 18;
    b = -60040;
    a = 29;
    d = d & b;
    c = 205;
    c = d ^ c;
    b = 125689;
    a = c * d;
    b = c != c;
    b = c == a;
    a = c > c;
    assert(d == 0);
    a = d <= c;
    a = d != a;
    c = b != b;
    b = 96024;
    b = -126168;
    b = c <= d;
    a = c ^ c;
    b = d > a;
    c = d != c;
    assert(c == 0);
    d = d != b;
    a = a | b;
    c = -328;
    a = c == d;
    c = c - b;
    b = 2929;
    b = 28202;
    assert(d == 0);
    c = d | c;
    assert(d == 0);
    a = a > d;
    c = 283;
    assert(a == 0);
    c = b == b;
    b = c ^ c;
    assert(d == 0);
    d = d > a;
    assert(a == 0);
    b = d == c;
    c = 366;
    b = c - a;
    b = d & d;
    c = d - c;
    d = c + b;
    c = -407;
    b = c - a;
    assert(a == 0);
    c = d ^ d;
    assert(c == 0);
    a = d < c;
    b = a != c;
    d = c != a;
    c = d ^ a;
    c = c > a;
    c = c - c;
    b = 101885;
    c = c >= b;
    d = a ^ a;
    d = a >= a;
    b = a | b;
    c = b * c;
    a = b << d;
    assert(c == 0);
    a = 26;
    d = b >> a;
    a = a | d;
    assert(d == 0);
    a = c + b;
    c = c ^ d;
    a = b & c;
    d = d < c;
    c = a - b;
    d = c + c;
    a = a < b;
    assert(d == 6);
    d = d >= d;
    d = a >= a;
    c = a - d;
    c = 48;
    c = a ^ b;
    b = -45809;
    b = 12;
    d = d >> b;
    a = c > d;
    c = c << a;
    assert(d == 0);
    assert(a == 1);
    d = 119;
    a = d >= a;
    assert(d == 119);
    func2_count += 1;
    }
    
    return 0; 
}

